name: mind_bubble
description: A calm desktop concept reminder application.
publish_to: none
version: 0.4.4

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dartloom:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom
  dartloom_singleton: ^0.1.0
  dartloom_singleton_socket:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_singleton_socket
  dartloom_sync:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_sync
  shared_preferences: ^2.5.5
  dartloom_storage_file:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_storage_file
  dartloom_storage: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  csv: ^6.0.0
  crypto: ^3.0.6
  excel: ^4.0.6
  file_picker: ^10.3.3
  flutter_markdown_plus: ^1.0.12
  flutter_riverpod: ^2.6.1
  http: ^1.6.0
  intl: any
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.4+4
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  image_path: assets/icon/mind_bubble.png
  android: true
  ios: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true

dependency_overrides:
  dartloom_settings:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_settings
  dartloom_sync:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_sync
  dartloom_logging:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_logging
  dartloom_resident:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_resident
  dartloom_singleton:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_singleton
  dartloom_storage:
    git:
      url: https://github.com/wkzMagician/dartloom.git
      ref: 20a3a537374349dd1c620ec4cd7a3517abebfc6c
      path: packages/dartloom_storage
