platforms:
  - android
  - ios
  - windows
  - macos
  - linux

packages:
  - dartloom
  - dartloom_singleton
  - dartloom_singleton_socket
  - dartloom_sync
  - dartloom_storage
  - dartloom_storage_file
